// flow-typed signature: fd4a6b1150efc37dd6a1ac8c00879c61
// flow-typed version: <<STUB>>/ddp-server-reactive_v^0.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ddp-server-reactive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ddp-server-reactive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ddp-server-reactive/example' {
  declare module.exports: any;
}

declare module 'ddp-server-reactive/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ddp-server-reactive/example.js' {
  declare module.exports: $Exports<'ddp-server-reactive/example'>;
}
declare module 'ddp-server-reactive/lib.js' {
  declare module.exports: $Exports<'ddp-server-reactive/lib'>;
}
